const movies = 
[
{"name":"Mummies: Secrets of the Pharaohs (a.k.a. Mummies 3D)","released_date":"2021-04-18","language":"Greek","country":"Brazil","genre":"Documentary|IMAX","description":"Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus."},
{"name":"Skyscraper Souls","released_date":"2021-07-13","language":"Irish Gaelic","country":"Indonesia","genre":"Drama|Romance","description":"Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus."},
{"name":"Life, Above All","released_date":"2021-03-19","language":"French","country":"Sweden","genre":"Drama","description":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio."},
{"name":"Love Is All You Need (Den skaldede frisør)","released_date":"2021-04-11","language":"Tamil","country":"Indonesia","genre":"Comedy|Drama|Romance","description":"Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis."},
{"name":"Mr. Baseball","released_date":"2021-04-28","language":"Aymara","country":"New Zealand","genre":"Comedy|Romance","description":"Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus."},
{"name":"Amos & Andrew","released_date":"2021-06-08","language":"Finnish","country":"China","genre":"Comedy","description":"Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc."},
{"name":"Mama's Boy","released_date":"2021-05-22","language":"Yiddish","country":"Indonesia","genre":"Comedy|Drama","description":"Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl."},
{"name":"24th Day, The","released_date":"2021-05-21","language":"Spanish","country":"Slovenia","genre":"Drama|Thriller","description":"Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem."},
{"name":"Boy Eats Girl","released_date":"2021-10-10","language":"German","country":"China","genre":"Comedy|Horror","description":"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit."},
{"name":"King of Texas, The","released_date":"2021-10-29","language":"Afrikaans","country":"Slovenia","genre":"Documentary","description":"Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est."},
{"name":"Me and Orson Welles","released_date":"2020-12-03","language":"Irish Gaelic","country":"Czech Republic","genre":"Drama","description":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum."},
{"name":"We Live Again","released_date":"2021-06-18","language":"Nepali","country":"Russia","genre":"Drama","description":"Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo."},
{"name":"City Lights","released_date":"2021-10-30","language":"Montenegrin","country":"Indonesia","genre":"Comedy|Drama|Romance","description":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat."},
{"name":"Card Player, The (Il cartaio)","released_date":"2021-01-21","language":"Pashto","country":"Japan","genre":"Crime|Horror|Mystery|Thriller","description":"Duis bibendum."},
{"name":"Robin-B-Hood (Bo bui gai wak)","released_date":"2021-01-20","language":"Malagasy","country":"Poland","genre":"Action|Comedy|Drama","description":"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst."}]

module.exports = movies